export const idbConfig = {
  databaseName: "media-db",
  version: 1,
  stores: [
    {
      name: "brand-videos",
      id: { keyPath: "id", autoIncrement: true },
      indices: [
        { name: "Link", keyPath: "Link" },
        { name: "videoName", keyPath: "videoName" },
        { name: "width", keyPath: "width" },
        { name: "height", keyPath: "height" },
        { name: "duration", keyPath: "duration" },
        { name: "fileSize", keyPath: "fileSize" },
        { name: "avatar", keyPath: "avatar" },
        { name: "thumbnails", keyPath: "thumbnails" },
        { name: "blurImage", keyPath: "blurImage" },
        { name: "waveformImage", keyPath: "waveformImage" },
      ],
    },
    {
      name: "brand-images",
      id: { keyPath: "id", autoIncrement: true },
      indices: [
        { name: "Link", keyPath: "Link" },
        { name: "videoName", keyPath: "videoName" },
        { name: "duration", keyPath: "duration" },
        { name: "fileSize", keyPath: "fileSize" },
        { name: "waveformImage", keyPath: "waveformImage" },
      ],
    },
    {
      name: "brand-logos",
      id: { keyPath: "id", autoIncrement: true },
      indices: [
        { name: "Link", keyPath: "Link" },
        { name: "logoName", keyPath: "logoName" },
      ],
    },
    {
      name: "brand-audio",
      id: { keyPath: "id", autoIncrement: true },
      indices: [
        { name: "Link", keyPath: "Link" },
        { name: "imageName", keyPath: "imageName" },
        { name: "duration", keyPath: "duration" },
        { name: "fileSize", keyPath: "fileSize" },
        { name: "waveformImage", keyPath: "waveformImage" },
      ],
    },
    {
      name: "stories",
      id: { keyPath: "id", autoIncrement: false },
      indices: [
        { name: "id", keyPath: "id", options: { unique: true } },
        { name: "status", keyPath: "status" },
        { name: "type", keyPath: "type" },
        { name: "question", keyPath: "question" },
        { name: "video_id", keyPath: "video_id" },
        { name: "video_link", keyPath: "video_link" },
        { name: "name", keyPath: "name" },
        { name: "revised_video", keyPath: "revised_video" },
        { name: "thumbnail_image", keyPath: "thumbnail_image" },
        { name: "created_at", keyPath: "created_at" },
        { name: "advocate_id", keyPath: "advocate_id" },
        { name: "role", keyPath: "role" },
        { name: "user_id", keyPath: "user_id" },
        { name: "profile_picture", keyPath: "profile_picture" },
        { name: "first_name", keyPath: "first_name" },
        { name: "last_name", keyPath: "last_name" },
      ],
    },
    {
      name: "uploaded-videos",
      id: { keyPath: "id", autoIncrement: false },
      indices: [
        { name: "id", keyPath: "id", options: { unique: true } },
        { name: "avatar", keyPath: "avatar" },
        { name: "waveformImage", keyPath: "waveformImage" },
        { name: "blurImage", keyPath: "companyId" },
        { name: "thumbnails", keyPath: "thumbnails" },
        { name: "filePath", keyPath: "filePath" },
        { name: "createdAt", keyPath: "createdAt" },
        { name: "videoId", keyPath: "videoId" },
        { name: "name", keyPath: "name" },
        { name: "contentType", keyPath: "contentType" },
        { name: "fileSize", keyPath: "fileSize" },
        { name: "contentId", keyPath: "contentId" },
        { name: "userId", keyPath: "userId" },
        { name: "width", keyPath: "fileSize" },
        { name: "height", keyPath: "height" },
        { name: "updatedAt", keyPath: "updatedAt" },
        { name: "subtitles", keyPath: "subtitles" },
        { name: "isAudio", keyPath: "isAudio" },
        { name: "duration", keyPath: "duration" },
        { name: "type", keyPath: "type" },
      ],
    },
    {
      name: "uploaded-audio",
      id: { keyPath: "id", autoIncrement: false },
      indices: [
        { name: "id", keyPath: "id", options: { unique: true } },
        { name: "avatar", keyPath: "avatar" },
        { name: "waveformImage", keyPath: "waveformImage" },
        { name: "blurImage", keyPath: "companyId" },
        { name: "thumbnails", keyPath: "thumbnails" },
        { name: "filePath", keyPath: "filePath" },
        { name: "createdAt", keyPath: "createdAt" },
        { name: "videoId", keyPath: "videoId" },
        { name: "name", keyPath: "name" },
        { name: "contentType", keyPath: "contentType" },
        { name: "fileSize", keyPath: "fileSize" },
        { name: "contentId", keyPath: "contentId" },
        { name: "userId", keyPath: "userId" },
        { name: "width", keyPath: "fileSize" },
        { name: "height", keyPath: "height" },
        { name: "updatedAt", keyPath: "updatedAt" },
        { name: "subtitles", keyPath: "subtitles" },
        { name: "isAudio", keyPath: "isAudio" },
        { name: "duration", keyPath: "duration" },
        { name: "type", keyPath: "type" },
        { name: "fileKey", keyPath: "fileKey" },
        { name: "files", keyPath: "files" },
        { name: "title", keyPath: "title" },
      ],
    },
    {
      name: "uploaded-images",
      id: { keyPath: "id", autoIncrement: false },
      indices: [
        { name: "id", keyPath: "id", options: { unique: true } },
        { name: "avatar", keyPath: "avatar" },
        { name: "waveformImage", keyPath: "waveformImage" },
        { name: "blurImage", keyPath: "companyId" },
        { name: "thumbnails", keyPath: "thumbnails" },
        { name: "filePath", keyPath: "filePath" },
        { name: "createdAt", keyPath: "createdAt" },
        { name: "videoId", keyPath: "videoId" },
        { name: "name", keyPath: "name" },
        { name: "contentType", keyPath: "contentType" },
        { name: "fileSize", keyPath: "fileSize" },
        { name: "contentId", keyPath: "contentId" },
        { name: "userId", keyPath: "userId" },
        { name: "width", keyPath: "fileSize" },
        { name: "height", keyPath: "height" },
        { name: "updatedAt", keyPath: "updatedAt" },
        { name: "subtitles", keyPath: "subtitles" },
        { name: "isAudio", keyPath: "isAudio" },
        { name: "duration", keyPath: "duration" },
        { name: "type", keyPath: "type" },
      ],
    },
  ],
};
